
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import models.Tokens.adminToken;

import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cesar
 */
public class AdminMenu extends javax.swing.JFrame {
    static adminToken mainToken = new adminToken();
    /**
     * Creates new form AdminMenu
     */
    public AdminMenu(adminToken admin) {
        if(admin.getNombre() == null){
            JOptionPane.showMessageDialog(null, "Error al iniciar sesión","Error",JOptionPane.ERROR_MESSAGE);
            this.dispose();
            System.exit(0);
        }else{
            mainToken = admin;
            initComponents();
            lblNombre.setText(mainToken.getNombre());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        btnShowTeachers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnShowTeachers1 = new javax.swing.JButton();
        btnShowTeachers2 = new javax.swing.JButton();
        btnShowTeachers3 = new javax.swing.JButton();
        lblAdvertencia = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(1132, 740, 740, 740));
        setMaximizedBounds(new java.awt.Rectangle(1132, 740, 740, 740));
        setMaximumSize(new java.awt.Dimension(1132, 740));
        setMinimumSize(new java.awt.Dimension(1132, 740));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1132, 740));
        setSize(new java.awt.Dimension(1132, 740));
        getContentPane().setLayout(null);

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1070, 20, 50, 40);

        btnExit1.setBackground(new java.awt.Color(255, 0, 0));
        btnExit1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(255, 255, 255));
        btnExit1.setText("Log out");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit1);
        btnExit1.setBounds(1010, 680, 110, 40);

        btnShowTeachers.setBackground(new java.awt.Color(30, 30, 50));
        btnShowTeachers.setFont(new java.awt.Font("Lemon", 1, 14)); // NOI18N
        btnShowTeachers.setForeground(new java.awt.Color(255, 255, 255));
        btnShowTeachers.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesar\\Documents\\Universidad_UNEDL\\4tosemestre\\Estructura_archivos\\EstructuraArchivos\\src\\main\\java\\resources\\icons\\information.png")); // NOI18N
        btnShowTeachers.setText("Calificaciones");
        btnShowTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTeachersActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowTeachers);
        btnShowTeachers.setBounds(800, 120, 240, 43);

        jLabel1.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        jLabel1.setText("Administrador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 30, 220, 50);

        btnShowTeachers1.setBackground(new java.awt.Color(30, 30, 50));
        btnShowTeachers1.setFont(new java.awt.Font("Lemon", 1, 14)); // NOI18N
        btnShowTeachers1.setForeground(new java.awt.Color(255, 255, 255));
        btnShowTeachers1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesar\\Documents\\Universidad_UNEDL\\4tosemestre\\Estructura_archivos\\EstructuraArchivos\\src\\main\\java\\resources\\icons\\teacher (1).png")); // NOI18N
        btnShowTeachers1.setText("Maestros");
        btnShowTeachers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTeachers1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowTeachers1);
        btnShowTeachers1.setBounds(20, 120, 240, 43);

        btnShowTeachers2.setBackground(new java.awt.Color(30, 30, 50));
        btnShowTeachers2.setFont(new java.awt.Font("Lemon", 1, 14)); // NOI18N
        btnShowTeachers2.setForeground(new java.awt.Color(255, 255, 255));
        btnShowTeachers2.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesar\\Documents\\Universidad_UNEDL\\4tosemestre\\Estructura_archivos\\EstructuraArchivos\\src\\main\\java\\resources\\icons\\boy-student.png")); // NOI18N
        btnShowTeachers2.setText("Alumnos");
        btnShowTeachers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTeachers2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowTeachers2);
        btnShowTeachers2.setBounds(280, 120, 240, 43);

        btnShowTeachers3.setBackground(new java.awt.Color(30, 30, 50));
        btnShowTeachers3.setFont(new java.awt.Font("Lemon", 1, 14)); // NOI18N
        btnShowTeachers3.setForeground(new java.awt.Color(255, 255, 255));
        btnShowTeachers3.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesar\\Documents\\Universidad_UNEDL\\4tosemestre\\Estructura_archivos\\EstructuraArchivos\\src\\main\\java\\resources\\icons\\book.png")); // NOI18N
        btnShowTeachers3.setText("Materias");
        btnShowTeachers3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTeachers3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowTeachers3);
        btnShowTeachers3.setBounds(540, 120, 240, 43);

        lblAdvertencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesar\\Documents\\Universidad_UNEDL\\4tosemestre\\Estructura_archivos\\EstructuraArchivos\\src\\main\\java\\resources\\icons\\alert.png")); // NOI18N
        lblAdvertencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdvertenciaMouseClicked(evt);
            }
        });
        getContentPane().add(lblAdvertencia);
        lblAdvertencia.setBounds(1060, 130, 30, 30);

        lblNombre.setFont(new java.awt.Font("Lemon", 0, 14)); // NOI18N
        lblNombre.setText("...");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(40, 50, 340, 19);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas cerrar sesión?", "Salir", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            Login newLogin = new Login();
            newLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnShowTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTeachersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowTeachersActionPerformed

    private void btnShowTeachers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTeachers1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowTeachers1ActionPerformed

    private void btnShowTeachers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTeachers2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowTeachers2ActionPerformed

    private void btnShowTeachers3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTeachers3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowTeachers3ActionPerformed

    private void lblAdvertenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdvertenciaMouseClicked
        JOptionPane.showMessageDialog(this, "En cada pestaña de los botones se podra modificar, eliminar, añadir y consultar cada uno de los registros", "WARNING", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_lblAdvertenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        UIManager.setLookAndFeel(new FlatMacDarkLaf());
        SwingUtilities.updateComponentTreeUI(new AdminMenu(mainToken));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu(mainToken).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnShowTeachers;
    private javax.swing.JButton btnShowTeachers1;
    private javax.swing.JButton btnShowTeachers2;
    private javax.swing.JButton btnShowTeachers3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
