/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import jdk.swing.interop.SwingInterOpUtils;
import models.Tokens.Token;
import models.Tokens.adminToken;
import models.Tokens.studentToken;

import javax.swing.*;

/**
 *
 * @author cesar
 */
public class AlumnosMenu extends javax.swing.JFrame {
    static studentToken mainToken = new studentToken();
    /**
     * Creates new form AlumnosMenu
     */
    public AlumnosMenu(studentToken token) {
        mainToken = token;
        initComponents();
        lblNombre.setText(token.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(1132, 740, 740, 740));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1132, 740));
        setMinimumSize(new java.awt.Dimension(1132, 740));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1132, 740));
        setSize(new java.awt.Dimension(1132, 740));
        getContentPane().setLayout(null);

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1070, 20, 50, 40);

        lblNombre.setFont(new java.awt.Font("Lemon", 0, 14)); // NOI18N
        lblNombre.setText("...");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(35, 26, 340, 19);

        btnExit1.setBackground(new java.awt.Color(255, 0, 0));
        btnExit1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(255, 255, 255));
        btnExit1.setText("Log out");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit1);
        btnExit1.setBounds(1010, 680, 110, 40);

        jButton1.setBackground(new java.awt.Color(30, 30, 50));
        jButton1.setFont(new java.awt.Font("Lemon", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesar\\Documents\\Universidad_UNEDL\\4tosemestre\\Estructura_archivos\\EstructuraArchivos\\src\\main\\java\\resources\\icons\\diploma-certificate.png")); // NOI18N
        jButton1.setText("Calificaciones");
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 160, 200, 43);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas cerrar sesión?", "Salir", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            new Login();
            this.dispose();
        }
    }//GEN-LAST:event_btnExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatMacDarkLaf());
        SwingUtilities.updateComponentTreeUI(new JFrame());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnosMenu(mainToken).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
