/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Repository.RepositorUnivesity;
import Repository.operations;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import models.Key;
import models.Tokens.Token;
import models.Tokens.studentToken;

import javax.swing.*;
<<<<<<< HEAD
import models.Tokens.teacherToken;
import org.json.simple.parser.JSONParser;
=======
>>>>>>> main

/**
 *
 * @author cesar
 */
public class Login extends javax. swing.JFrame {
<<<<<<< HEAD
    static String username;
    
=======
>>>>>>> main
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(1132, 740, 740, 740));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1132, 740));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1132, 740));
        getContentPane().setLayout(null);

        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(30, 290, 300, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 350, 110, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PSICOANALISTA SCHOOL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 70, 400, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 250, 80, 22);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(30, 390, 300, 30);

        btnLogin.setBackground(new java.awt.Color(55, 151, 119));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(30, 460, 300, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("------------------------------------------------");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 260, 16);

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1060, 20, 50, 40);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 70, 900, 640);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INICIO DE SESIÓN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 150, 240, 22);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        RepositorUnivesity repository = new operations();
        Key key = new Key();

        String username = txtUsuario.getText();
        String password = txtPassword.getText();

        key = repository.login(username, password);

        if(key.getMatricula() != null && key.getToken() != null){
            if(key.getToken().equalsIgnoreCase("alumno")){
<<<<<<< HEAD
             Token student = new studentToken();
             student.initInformation(key.getMatricula());
            }else if(key.getToken().equalsIgnoreCase("maestro")){               
                Token teacher=new teacherToken();
                teacher.initInformation(key.getMatricula());             
                new VentanaMaestro(key.getMatricula()).setVisible(true);           
                dispose();
                
                
                
=======
                studentToken student = new studentToken();
                student.initInformation(key.getMatricula());
                AlumnosMenu alumnosMenu = new AlumnosMenu(student);
                alumnosMenu.setVisible(true);
                this.dispose();
>>>>>>> main
            }
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    public void clean(){
        txtUsuario.setText("");
        txtPassword.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {

        UIManager.setLookAndFeel(new FlatMacDarkLaf());
        SwingUtilities.updateComponentTreeUI(new Login());

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
